#!/usr/bin/env sh
# prometheus gateway server info
HOST="prometheus-pushgateway"
PORT="9091"
PROTOCOL="http"

push_prometheus() {
  metric_name="$1"
  value="$2"
  instance="$3"
  cat <<EOF | curl -sSL --data-binary @- ${PROTOCOL}://${HOST}:${PORT}/metrics/job/my_exporter/instance/$instance
  # HELP $metric_name Metric autogenerated by my customized application
  # TYPE $metric_name gauge
  $metric_name{provider="app1"} $value
EOF
}
# how to use it?
#push_prometheus "$prometheus_metric_name" "$value" "$instance"

while true; do
  push_prometheus "web_active_users" "$(($RANDOM%10))" "web_frontend_server1"
  push_prometheus "web_active_users" "$(($RANDOM%10))" "web_frontend_server2"
  push_prometheus "web_active_users" "$(($RANDOM%10))" "web_frontend_server3"
  sleep 15
done